version: "2"
services:
  jenkins:
    build:
      context: ./docker-jenkins
    image: getrostt/jenkins:2.34.0
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run:/var/run:rw
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - 'wildfly:wildfly'

  wildfly:
    build:
      context: ./docker-wildfly
    image: getrostt/wildfly:10.1.0.Final
    ports:
      - 8180:8080
      - 9990:9990
